apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-pv
  labels:
    type: local
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  hostPath:
    path: /var/snap/microk8s/common/comfyui