apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-pvc
  namespace: comfyui
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: microk8s-hostpath