apiVersion: v1
kind: Service
metadata:
  name: comfyui
  namespace: comfyui
  labels:
    app: comfyui
spec:
  type: ClusterIP
  ports:
    - port: 8188
      targetPort: 8188
      protocol: TCP
      name: http
  selector:
    app: comfyui