apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: comfyui

commonLabels:
  app.kubernetes.io/name: comfyui
  app.kubernetes.io/managed-by: kustomize

resources:
  - storage/
  - comfyui/
  - comfyui-mcp/