{{- if and .Values.comfyui.ingress.enabled .Values.comfyui.ingress.host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "comfyui.fullname" . }}
  namespace: {{ include "comfyui.namespace" . }}
  labels:
    {{- include "comfyui.labels" . | nindent 4 }}
  {{- with .Values.comfyui.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.comfyui.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - host: {{ .Values.comfyui.ingress.host }}
      http:
        paths:
          - path: {{ .Values.comfyui.ingress.path }}
            pathType: {{ .Values.comfyui.ingress.pathType }}
            backend:
              service:
                name: {{ include "comfyui.fullname" . }}
                port:
                  number: {{ .Values.comfyui.service.port }}
  {{- with .Values.comfyui.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
